src/Pasifika.WebUI/Areas/Admin/Controllers/DestinoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Business.Abstract;
using Pasifika.Model;

namespace Pasifika.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    public class DestinoController : Controller
    {
        private readonly IDestinoBusiness _destino;
        private readonly IRegionBusiness _region;

        public DestinoController(IDestinoBusiness d, IRegionBusiness r)
        {
            this._destino = d;
            this._region = r;
        }

        public ActionResult List(int regionId)
        {
            var d = _destino.GetByRegion(regionId);
            var r = _region.Get(regionId);

            return View(new ViewModels.DestinoListViewModel
            {
                Destinos = d,
                Region = r
            });
        }

        public ViewResult Create(int regionId)
        {
            var d = new Destino();
            d.RegionId = regionId;

            return View("Edit", new ViewModels.DestinoEditViewModel
            {
                Destino = d
            });
        }

        public ViewResult Edit(int id)
        {
            var d = _destino.Get(id);

            return View(new ViewModels.DestinoEditViewModel
            {
                Destino = d
            });
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Destino d, HttpPostedFileBase file1 = null, HttpPostedFileBase file2 = null, HttpPostedFileBase file3 = null, HttpPostedFileBase filePDFGuia = null, IEnumerable<string> Titulo = null, IEnumerable<string> Texto = null)
        {
            if (file1 != null)
            {
                d.FotoGuia = file1.FileName;
                d.StreamGuia = file1.InputStream;
            }

            if (file2 != null)
            {
                d.FotoHotel = file2.FileName;
                d.StreamHotel = file2.InputStream;
            }

            if (file3 != null)
            {
                d.FotoExcursion = file3.FileName;
                d.StreamExcursion = file3.InputStream;
            }

            if (filePDFGuia != null)
            {
                d.PDFGuia = filePDFGuia.FileName;
                d.StreamPDFGuia = filePDFGuia.InputStream;
            }

            _destino.Guardar(d, Server.MapPath("~/Content"), Titulo, Texto);

            return RedirectToAction("List", new
            {
                regionId = d.RegionId
            });
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            int regionId = _destino.Get(Id).RegionId;
            _destino.Delete(Id);

            return RedirectToAction("List", new
            {
                regionId = regionId
            });
        }

        [HttpPost]
        public ActionResult Order(string txtJsonOrden, int regionId)
        {
            _destino.Order(txtJsonOrden);

            return RedirectToAction("List", new
            {
                regionId = regionId
            });
        }
    }
}

src/Pasifika.WebUI/Areas/Admin/Views/Destino/Edit.cshtml
@model Pasifika.WebUI.Areas.Admin.ViewModels.DestinoEditViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<script id="template-texto" type="x-tmpl-mustache">
    <div class="itemTexto panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><button class="btnEliminarTexto btn btn-danger btn-xs">Eliminar</button><button class="btnSubirTexto btn btn-primary btn-xs"><i class="fa fa-angle-up"></i></button><button class="btnBajarTexto btn btn-primary btn-xs"><i class="fa fa-angle-down"></i></button></h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label class="col-md-2 control-label">Titulo</label>
                <div class="col-md-9">
                    <input type="text" name="Titulo" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">Texto</label>
                <div class="col-md-9">
                    <textarea name="Texto" class="summernote"></textarea>
                </div>
            </div>
        </div>
    </div>
</script>

@using (Html.BeginForm("Edit", "Destino", FormMethod.Post, new { id = "formEdit", enctype = "multipart/form-data" }))
{
    <div class="jarviswidget" id="wid-id-10">
        <header>
            <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
            <h2>Destinos </h2>

        </header>

        <!-- widget div-->
        <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
            </div>

            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
                <div class="form-horizontal">
                    <fieldset>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Nombre</label>
                            <div class="col-md-9">
                                @Html.TextBox("Nombre", Model.Destino.Nombre, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Url</label>
                            <div class="col-md-9">
                                @Html.TextBox("Url", Model.Destino.Url, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Foto Guia</label>
                            <div class="col-md-9">
                                @if (Model.Destino.FotoGuia != null)
                                {
                                    @Html.Hidden("FotoGuia", Model.Destino.FotoGuia)
                                    <img src="~/Content/images/destino/guia/@Model.Destino.FotoGuia" width="50" height="50" /><br />
                                }
                                <input type="file" name="file1" class="col-lg-12" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Foto Hotel</label>
                            <div class="col-md-9">
                                @if (Model.Destino.FotoHotel != null)
                                {
                                    @Html.Hidden("FotoHotel", Model.Destino.FotoHotel)
                                    <img src="~/Content/images/destino/hotel/@Model.Destino.FotoHotel" width="50" height="50" /><br />
                                }
                                <input type="file" name="file2" class="col-lg-12" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Foto Excursion</label>
                            <div class="col-md-9">
                                @if (Model.Destino.FotoExcursion != null)
                                {
                                    @Html.Hidden("FotoExcursion", Model.Destino.FotoExcursion)
                                    <img src="~/Content/images/destino/excursion/@Model.Destino.FotoExcursion" width="50" height="50" /><br />
                                }
                                <input type="file" name="file3" class="col-lg-12" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">PDF Guia</label>
                            <div class="col-md-9">
                                @Html.Hidden("PDF", Model.Destino.PDFGuia)
                                @if (!String.IsNullOrEmpty(Model.Destino.PDFGuia))
                                {
                                    <a href="javascript:void(0)" onclick="$(this).parent().find('input[type=\'hidden\']').val('')"><i class="fa fa-times"></i></a>
                                }
                                <input type="file" name="filePDFGuia" class="form-control">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-2 control-label">Alt</label>
                            <div class="col-md-9">
                                @Html.TextBox("Alt", Model.Destino.Alt, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Resumen</label>
                            <div class="col-md-9">
                                @Html.TextArea("Resumen", (Model.Destino.Resumen), new { @class = "summernote", @cols = 40, @rows = 6 })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">Datos</label>
                            <div class="col-md-9">
                                @Html.TextArea("Datos", @Model.Destino.Datos, new { @cols = 40, @rows = 6 })
                            </div>
                        </div>
                    </fieldset>

                    <fieldset id="divTexto">
                        <legend>Textos <button id="btnAgregarTexto" class="btn btn-primary btn-xs">Agregar</button></legend>
                        @foreach(var dt in Model.Destino.DestinoTitulos.OrderBy(x => x.Orden))
                        { 
                            <div class="itemTexto panel panel-default">
                                <div class="panel-heading">
                                    <h3 class="panel-title"><button class="btnEliminarTexto btn btn-danger btn-xs">Eliminar</button><button class="btnSubirTexto btn btn-primary btn-xs"><i class="fa fa-angle-up"></i></button><button class="btnBajarTexto btn btn-primary btn-xs"><i class="fa fa-angle-down"></i></button></h3>
                                </div>
                                <div class="panel-body">
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">Titulo</label>
                                        <div class="col-md-9">
                                            @Html.TextBox("Titulo", dt.Titulo, new { @class = "form-control" })
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-2 control-label">Texto</label>
                                        <div class="col-md-9">
                                            @Html.TextArea("Texto", (dt.Texto), new { @class = "summernote", @cols = 40, @rows = 6 })
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </fieldset>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.Hidden("RegionId", Model.Destino.RegionId, new { @class = "form-control" })
                                <input id="btnEnviar" type="submit" class="btn btn-primary" value="Guardar" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end widget content -->
        </div>
    </div>
}

@section scripts
{
    <script src="~/Areas/Admin/Content/js/libs/mustache.js"></script>
    <script src="~/Areas/Admin/Content/js/plugin/ckeditor/config.js"></script>
    <script src="~/Areas/Admin/Content/js/plugin/ckeditor/ckeditor.js"></script>
    <script src="~/Areas/Admin/Content/js/plugin/ckeditor/styles.js"></script>
    <script src="~/Areas/Admin/Content/js/plugin/ckeditor/adapters/jquery.js"></script>

    <script type="text/javascript">
        /*
        $('#divTexto').sortable({
            items: ".itemTexto"
        }).disableSelection();
        */

        $(document).ready(function () {
            $('.summernote').ckeditor({

            });
        });

        $('#btnAgregarTexto').click(function (e) {
            e.preventDefault();

            var template = $('#template-texto').html();
            Mustache.parse(template);   // optional, speeds up future uses
            var rendered = Mustache.render(template, {  });
            $('#divTexto').append(rendered);

            var sn = $('#divTexto .itemTexto:last .summernote');

            sn.ckeditor({
                height: 180,
                focus: false,
                tabsize: 2
            });
        });

        $('body').on('click', '.btnEliminarTexto', function (e) {
            e.preventDefault();

            $(this).closest('.itemTexto').remove();
        });

        $('body').on('click', '.btnSubirTexto', function (e) {
            e.preventDefault();

            $(this).parents('.itemTexto').insertBefore($(this).parents('.itemTexto').prev());
        });

        $('body').on('click', '.btnBajarTexto', function (e) {
            e.preventDefault();

            $(this).parents('.itemTexto').insertAfter($(this).parents('.itemTexto').next());
        });

        $('#btnEnviar').click(function (e) {
            e.preventDefault();

            $("#formEdit").submit();
        });
    </script>
}

src/Pasifika.WebUI/Areas/Admin/Views/Destino/List.cshtml
@model Pasifika.WebUI.Areas.Admin.ViewModels.DestinoListViewModel
@{
    ViewBag.Title = "List";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!-- Widget ID (each widget will need unique ID)-->
<div class="jarviswidget" id="wid-id-0">
    <header>
        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
        <h2>Destinos </h2>

    </header>

    <!-- widget div-->
    <div>

        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
        </div>
        <!-- end widget edit box -->
        <!-- widget content -->
        <div class="widget-body no-padding">
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="col-lg-1">Código</th>
                                <th class="col-lg-11">Destino</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody class="tbody">
                            @foreach (var d in Model.Destinos)
                            {
                                <tr data-id="@d.Id">
                                    <td>
                                        @Html.ActionLink(d.Id.ToString(), "Edit", new
                                            {
                                                id = d.Id
                                            })
                                    </td>
                                    <td>@d.Nombre</td>
                                    <td>
                                        @Html.ActionLink("Ciudad", "List", "Ciudad", new
                                        {
                                            destinoId = d.Id
                                        }, null)
                                    </td>
                                    <td>
                                        @using (Html.BeginForm("Delete", "Destino"))
                                        {
                                            @Html.Hidden("Id", d.Id)
                                            <input type="submit" class="btn btn-default btn-xs" value="Delete" />
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="widget-footer padding-bottom-10">
                @using (Html.BeginForm("Order", "Destino", FormMethod.Post, new { id = "formEdit" }))
                {
                    @Html.Hidden("txtJsonOrden")
                    @Html.Hidden("regionId", Model.Region.Id)
                    <input id="btnEnviar" type="button" class="btn btn-primary" value="Guardar Orden" />
                    @Html.ActionLink("Nuevo Destino", "Create", new { regionId = Model.Region.Id }, new { @class = "btn btn-primary" })
                }
            </div>
        </div>
    </div>
    <!-- end widget content -->
</div>
<!-- end widget div -->

@section scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('.tbody').sortable({}).disableSelection();

            $('#btnEnviar').click(function (e) {
                e.preventDefault();

                var orden = [];
                $('.tbody tr').each(function (i, row) {
                    orden.push($(row).attr('data-id'));
                });

                $('#txtJsonOrden').val(JSON.stringify(orden));

                $("#formEdit").submit();
            });
        });
    </script>
}