src/Pasifika.WebUI/Areas/Admin/Controllers/NotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;
using System.IO;

namespace Pasifika.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    public class NotaController : Controller
    {
        private readonly INotaBusiness _nota;
        public NotaController(INotaBusiness n)
        {
            this._nota = n;
        }

        public ActionResult List()
        {
            var n = _nota.Get(null, null, null);

            return View(new ViewModels.NotaListViewModel
            {
                Notas = n
            });
        }

        public ViewResult Create()
        {
            var n = new Nota();
            n.Fecha = DateTime.Now;

            return View("Edit", new ViewModels.NotaEditViewModel
            {
                Nota = n
            });
        }

        public ViewResult Edit(int id)
        {
            var n = _nota.Get(id);

            string texto = "";

            if (System.IO.File.Exists(Server.MapPath("~/Content/images/nota") + "\\" + n.Id.ToString() + ".html"))
            {
                using (var tr = new StreamReader(Server.MapPath("~/Content/images/nota") + "\\" + n.Id.ToString() + ".html"))
                {
                    texto = tr.ReadToEnd();
                }
            }

            return View(new ViewModels.NotaEditViewModel
            {
                Nota = n,
                Texto = texto
            });
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Nota n, string Texto)
        {
            _nota.Guardar(n, Texto, Server.MapPath("~/Content"));

            return RedirectToAction("List", new
            {

            });
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            _nota.Delete(Id);

            return RedirectToAction("List");
        }   
    }
}

src/Pasifika.WebUI/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class BannerController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public BannerController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        //tipo: 1 -> grande; 2 -> chico
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId, int tipo)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            List<Banner> b = new List<Banner>();

            if (p != null)
                b = p.Banners.ToList();

            if (tipo == 1)
                return PartialView("Cargar", b);
            else
                if (tipo == 2)
                    return PartialView("CargarChico", b);
                else
                    return PartialView("Cargar", b);
        }
    }
}

src/Pasifika.WebUI/Controllers/MetatagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class MetatagController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public MetatagController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            if (p != null)
            {
                if (p.MetaTags.Count > 0)
                {
                    MetaTag mt = p.MetaTags.FirstOrDefault();
                    ViewBag.Title = mt.Title;
                    ViewBag.MetaDescription = mt.Description;
                    ViewBag.MetaKeywords = mt.Keywords;
                }
            }

            return PartialView();
        }
    }
}

src/Pasifika.WebUI/Controllers/NotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Business.Abstract;
using System.IO;
using MvcSiteMapProvider;

namespace Pasifika.WebUI.Controllers
{
    public class NotasController : Controller
    {
        private readonly INotaBusiness _nota;
        
        public NotasController(INotaBusiness n)
        {
            this._nota = n;
        }
        
        [MvcSiteMapNodeAttribute(Title = "Notas", ParentKey = "Home", Key = "Notas")]
        public ActionResult Index(int? pagina)
        {
            int page = 1;
            int cantidadPagina = 6;
            if (pagina.HasValue)
                page = pagina.Value;

            var n = _nota.GetPaginado(null, null, true, page, cantidadPagina);
            var nd = _nota.Get(null, null, true);

            int maxPage = 0;

            if (n.Count > 0)
            {
                int totalRows = nd.Count();

                if (totalRows % cantidadPagina > 0)
                    maxPage = (totalRows / cantidadPagina) + 1;
                else
                    maxPage = totalRows / cantidadPagina;

            }

            string linkAnterior = "";
            string linkSiguiente = "";

            if (page - 1 > 0)
                linkAnterior = Url.RouteUrl(new { controller = "Notas", action = "Index", Pagina = page - 1 });

            if (page + 1 <= maxPage)
                linkSiguiente = Url.RouteUrl(new { controller = "Notas", action = "Index", Pagina = page + 1 });

            ViewBag.menusseleccionado = "Notas";

            return View(new ViewModels.NotasIndexViewModel
            {
                Notas = n,
                NotasDirectorio = nd,
                Pagina = page,
                CantidadPagina = maxPage,
                linkAnterior = linkAnterior,
                linkSiguiente = linkSiguiente
            });
        }

        [MvcSiteMapNodeAttribute(Title = "Notas", ParentKey = "Home", DynamicNodeProvider = "Pasifika.WebUI.DI.DynamicNodeProvider.NotaIndexDynamicNodeProvider, Pasifika.WebUI")]
        public ActionResult IndexAnoMes(int ano, int mes, int? pagina)
        {
            int page = 1;
            int cantidadPagina = 6;
            if (pagina.HasValue)
                page = pagina.Value;

            var n = _nota.GetPaginado(ano, mes, true, page, cantidadPagina);
            var notasTotal = _nota.Get(ano, mes, true);
            var nd = _nota.Get(null, null, true);

            int maxPage = 0;

            if (n.Count > 0)
            {
                int totalRows = notasTotal.Count();

                if (totalRows % cantidadPagina > 0)
                    maxPage = (totalRows / cantidadPagina) + 1;
                else
                    maxPage = totalRows / cantidadPagina;

            }

            string linkAnterior = "";
            string linkSiguiente = "";

            if (page - 1 > 0)
                linkAnterior = Url.RouteUrl("notasFecha", new { ano = ano, mes = mes, Pagina = page - 1 });

            if (page + 1 <= maxPage)
                linkSiguiente = Url.RouteUrl("notasFecha", new { ano = ano, mes = mes, Pagina = page + 1 });

            ViewBag.menusseleccionado = "Notas";

            return View("Index", new ViewModels.NotasIndexViewModel
            {
                Notas = n,
                NotasDirectorio = nd,
                Pagina = page,
                CantidadPagina = maxPage,
                linkAnterior = linkAnterior,
                linkSiguiente = linkSiguiente
            });
        }

        [MvcSiteMapNodeAttribute(Title = "Nota", ParentKey = "Notas", DynamicNodeProvider = "Pasifika.WebUI.DI.DynamicNodeProvider.NotaDetailsDynamicNodeProvider, Pasifika.WebUI")]
        public ActionResult Detalle(string url)
        {
            var n = _nota.GetByUrl(url);

            if (url == "preguntas-frecuentes")
                ViewBag.menusseleccionado = "preguntas-frecuentes";
            else
            { 
                if(n.Visible)
                    ViewBag.menusseleccionado = "Notas";
            }
                

            string texto = "";


            if (System.IO.File.Exists(Server.MapPath("~/Content/images/nota") + "\\" + n.Id.ToString() + ".html"))
            {
                using (var tr = new StreamReader(Server.MapPath("~/Content/images/nota") + "\\" + n.Id.ToString() + ".html"))
                {
                    texto = tr.ReadToEnd();
                }
            }

            return View(new ViewModels.NotasDetalleViewModel
            {
                Nota = n,
                Texto = texto
            });
        }
    }
}

src/Pasifika.WebUI/Controllers/SugeridoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class SugeridoController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public SugeridoController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            List<SugerenciaPagina> s = new List<SugerenciaPagina>();

            if (p != null)
                s = p.SugerenciasPagina.ToList();

            return PartialView(s);
        }
    }
}

src/Pasifika.WebUI/Views/Notas/Detalle.cshtml
@model Pasifika.WebUI.ViewModels.NotasDetalleViewModel
@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section header
{
    @Html.Action("Cargar", "Metatag", new { notaId = Model.Nota.Id })
}

<div class="row">
    <div class="col-xs-12">

        <div class="row">
            <div class="col-xs-12">
                <div class="borde-top-gris">
                    <h1 class="titular-1 f-linea-gris text-center">
                        <span>@Model.Nota.Titulo</span>
                    </h1>
                </div>
            </div>
        </div>

    </div>
</div>

@Html.Action("Cargar", "Banner", new { notaId = Model.Nota.Id, tipo = 2 })


<div class="row modulo">
    <div class="col-xs-12">
        <div class="borde-top-gris">
            @if (Model.Nota.Resumen != null && Model.Nota.Resumen.Trim() != "")
            {
                <p class="texto-21 texto-destacado">
                    @Html.Raw(Model.Nota.Resumen)
                </p>
            }
        </div>
    </div>
</div>



<div class="row modulo">
    <div class="col-xs-12">
        <p class="texto-5">
            @Html.Raw(Model.Texto)
        </p>
    </div>
</div>

@if (Model.Nota.Visible)
{ 
<div class="row modulo">
    <div class="col-xs-12">
        <div class="borde-top-gris">
            <h4 class="titular-1 f-linea-gris">
                <span>Tambi&eacute;n le puede interesar</span>
            </h4>
        </div>
    </div>
</div>

@Html.Action("Cargar", "Sugerido", new { notaId = Model.Nota.Id })
}

@section scripts
{
    <script>
        $(function () {

            $('.flexslider').flexslider({
                animation: "fade",
                controlNav: true,
                directionNav: true
            });
        });
    </script>
}

src/Pasifika.WebUI/Views/Notas/Index.cshtml
@model Pasifika.WebUI.ViewModels.NotasIndexViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section header
{
    @Html.Action("Cargar", "Metatag", new { seccionId = 20 })
}

<div class="row">
    <div class="col-xs-12">

        <div class="row">
            <div class="col-xs-12">
                <div class="borde-top-gris">
                    <h1 class="titular-1 f-linea-gris text-center">
                        <span>Notas</span>
                    </h1>
                </div>
            </div>
        </div>

    </div>
</div>

@Html.Action("Cargar", "Banner", new { seccionId = 20, tipo = 2 })

<div class="row modulo">
    <div class="col-md-9 col-sm-12">
        
        @foreach(var n in Model.Notas)
        { 
            <div class="row">
                <div class="col-xs-12">
                    <div class="resumen-nota">
                        <p class="bold">@n.Titulo</p>
                        <a href="@Url.RouteUrl(new { controller = "Notas" ,
                                          action = "Detalle",
                                          url = n.Url })"><h2 class="texto-25 bold">@n.SubTitulo</h2></a>
                        <p class="texto-16 fecha">@n.Fecha.ToString("d \\de MMMM \\de yyyy")</p>
                        <p class="texto-5">
                            @Html.Raw(n.Resumen)
                        </p>
                    </div>
                </div>
            </div>
        }
        <div class="row modulo">
            <div class="col-xs-12">
                <nav>
                    <ul class="pager">
                        <li class="previous">
                            @if (!string.IsNullOrEmpty(Model.linkAnterior))
                            {
                                <a href="@Model.linkAnterior"><span aria-hidden="true" class="ico flecha-izq"></span> PÁGINA ANTERIOR</a>
                            }
                        </li>
                        <li class="next">
                            @if (!string.IsNullOrEmpty(Model.linkSiguiente))
                            {
                                <a href="@Model.linkSiguiente">PÁGINA SIGUIENTE <span aria-hidden="true" class="ico flecha-der"></span></a>
                            }
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
      
    </div>
    <!-- / Col izquierda -->

    <div class="col-md-3 hidden-sm">
        <div class="row modulo">
            <div class="col-xs-12">
                <div class="bloque-gris text-center">
                    <p class="texto-25">
                        <strong>Directorio:</strong>
                    </p>

                    @{
                        var qNotas = from n in Model.NotasDirectorio
                                     group n by n.Fecha.Year into notasAnos
                                     
                                     orderby notasAnos.Key descending
                                     select new
                                     {
                                         year = notasAnos.Key,
                                         months = from o in notasAnos
                                                  group o by o.Fecha.Month into notasMeses
                                                  select new 
                                                  {
                                                    month = notasMeses.Key,
                                                    notas = notasMeses.OrderByDescending(x => x.Fecha)
                                                  }
                                     };
                    }

                    <ul class="list-unstyled texto-5">
                        @foreach (var y in qNotas.ToList())
                        {
                            <li>
                                <strong>@y.year:</strong>
                                <ul class="list-unstyled ">
                                    @foreach(var m in y.months)
                                    {
                                        <li>
                                            @{
                                                string text = m.notas.First().Fecha.ToString("MMMM", System.Globalization.CultureInfo.CurrentCulture);
                                            }
                                            <a href="@Url.RouteUrl("notasFecha", new { 
                                                        ano = y.year,
                                                        mes = m.month})">@(char.ToUpper(text[0]) + ((text.Length > 1) ? text.Substring(1).ToLower() : string.Empty)) (@m.notas.Count().ToString().PadLeft(2, '0'))</a>
                                        </li>
                                    }
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>

@section scripts
{
    <script>
        $(function () {

            $('.flexslider').flexslider({
                animation: "fade",
                controlNav: true,
                directionNav: true
            });
        });
    </script>
}