src/Pasifika.WebUI/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class BannerController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public BannerController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        //tipo: 1 -> grande; 2 -> chico
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId, int tipo)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            List<Banner> b = new List<Banner>();

            if (p != null)
                b = p.Banners.ToList();

            if (tipo == 1)
                return PartialView("Cargar", b);
            else
                if (tipo == 2)
                    return PartialView("CargarChico", b);
                else
                    return PartialView("Cargar", b);
        }
    }
}

src/Pasifika.WebUI/Controllers/ColaboradoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Business.Abstract;
using MvcSiteMapProvider;

namespace Pasifika.WebUI.Controllers
{
    public class ColaboradoresController : Controller
    {
        private readonly IPartnerBusiness _partner;
        public ColaboradoresController(IPartnerBusiness p)
        {
            this._partner = p;
        }

        [MvcSiteMapNodeAttribute(Title = "Colaboradores", ParentKey = "Home", Key = "Colaboradores")]
        public ActionResult Index()
        {
            ViewBag.menusseleccionado = "Colaboradores";
            var p = _partner.Get();

            return View(new ViewModels.ColaboradoresIndexViewModel
            {
                Partners = p
            });
        }
    }
}

src/Pasifika.WebUI/Controllers/MetatagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class MetatagController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public MetatagController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            if (p != null)
            {
                if (p.MetaTags.Count > 0)
                {
                    MetaTag mt = p.MetaTags.FirstOrDefault();
                    ViewBag.Title = mt.Title;
                    ViewBag.MetaDescription = mt.Description;
                    ViewBag.MetaKeywords = mt.Keywords;
                }
            }

            return PartialView();
        }
    }
}

src/Pasifika.WebUI/Controllers/TextoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class TextoController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public TextoController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            string texto = "";

            if (p != null)
            {
                var t = p.PaginaTextos.FirstOrDefault();
                if (t != null)
                    texto = t.Texto;
            }

            
            return PartialView(model: texto);
        }
    }
}

src/Pasifika.WebUI/Views/Colaboradores/Index.cshtml
@model Pasifika.WebUI.ViewModels.ColaboradoresIndexViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section header
{
    @Html.Action("Cargar", "Metatag", new { seccionId = 22 })
}

<div class="row">
    <div class="col-xs-12">

        <div class="row">
            <div class="col-xs-12">
                <div class="borde-top-gris">
                    <h1 class="titular-1 f-linea-gris text-center">
                        <span>COLABORADORES</span>
                    </h1>
                </div>
            </div>
        </div>

    </div>
</div>

@Html.Action("Cargar", "Banner", new { seccionId = 22, tipo = 2 })

<div class="row">
    <div class="col-xs-12">
        <p class="titular-2 texto-destacado">
            @Html.Action("Cargar", "Texto", new { seccionId = 22 })
        </p>
    </div>
</div>

<div class="thumbnails modulo">
    <!-- row thumbs -->
    <div class="row">
        @{int cant = 0;}
        @foreach (var p in Model.Partners)
        {
        <!-- thumb-->
            <div class="col-sm-4 col-xs-6 text-center texto-altura-fija">
                @if (p.Link != null && p.Link != "")
                {
                    <a href="@p.Link" class="thumbnail no-hover no-border">
                        <img alt="" src="~/Content/images/partner/@p.Foto" class="img-responsive">
                        <div class="caption">
                            <h2 class="texto-6">@p.Nombre</h2>
                            <p class="texto-5">@Html.Raw(p.Texto)</p>
                        </div>
                    </a>
                }
                else
                {
                    <div class="thumbnail no-hover no-border">
                        <img alt="" src="~/Content/images/partner/@p.Foto" class="img-responsive">
                        <div class="caption">
                            <h2 class="texto-6">@p.Nombre</h2>
                            <p class="texto-5">@Html.Raw(p.Texto)</p>
                        </div>
                    </div>
                }
            </div>

            /*cant++;
            if (cant % 3 == 0)
            {
                @:</div>
                @:<div class="row">
            }*/
        }
    </div>
</div>

@section scripts
{
    <script>
        $(function () {
            $('.flexslider').flexslider({
                animation: "fade",
                controlNav: true,
                directionNav: true
            });
        });
    </script>
}