src/Pasifika.WebUI/Areas/Admin/Controllers/PaginaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Business.Abstract;
using Pasifika.Model;

namespace Pasifika.WebUI.Areas.Admin.Controllers
{
    [Authorize]
    public class PaginaController : Controller
    {
        private readonly IPaginaBusiness _pagina;
        private readonly ITagBusiness _tag;
        private readonly ISeccionBusiness _seccion;
        private readonly IDestinoBusiness _destino;
        private readonly IRegionBusiness _region;

        public PaginaController(IPaginaBusiness p, ITagBusiness t, ISeccionBusiness s, IDestinoBusiness  d, IRegionBusiness r)
        {
            this._pagina = p;
            this._tag = t;
            this._seccion = s;
            this._destino = d;
            this._region = r;
        }

        public ActionResult List()
        {
            var p = _pagina.Get();

            return View(new ViewModels.PaginaListViewModel
            {
                Paginas = p                
            });
        }

        public ViewResult Create()
        {
            Pagina p = new Pagina();
            var t = _tag.Get();
            var s = _seccion.Get();
            var d = _destino.Get();
            var r = _region.Get();

            return View("Edit", new ViewModels.PaginaEditViewModel
            {
                Pagina = p,
                Tags = t,
                Secciones = s,
                Destinos = d,
                Regiones = r
            });
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            _pagina.Delete(Id);

            return RedirectToAction("List", new
            {
                
            });
        }

        public ViewResult Edit(int id)
        {
            Pagina p = _pagina.Get(id);
            var t = _tag.Get();
            var s = _seccion.Get();
            var d = _destino.Get();
            var r = _region.Get();

            return View(new ViewModels.PaginaEditViewModel
            {
                Pagina = p,
                Tags = t,
                Secciones = s,
                Destinos = d,
                Regiones = r
            });
        }

        [HttpPost]
        public ActionResult Edit(Pagina p)
        {
            _pagina.Guardar(p);

            return RedirectToAction("List", new
            {

            });
        }

        [HttpPost]
        public ActionResult Order(string txtJsonOrden)
        {
            _pagina.Order(txtJsonOrden);

            return RedirectToAction("List", new
            {
                
            });
        }
    }
}

src/Pasifika.WebUI/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class BannerController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public BannerController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        //tipo: 1 -> grande; 2 -> chico
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId, int tipo)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            List<Banner> b = new List<Banner>();

            if (p != null)
                b = p.Banners.ToList();

            if (tipo == 1)
                return PartialView("Cargar", b);
            else
                if (tipo == 2)
                    return PartialView("CargarChico", b);
                else
                    return PartialView("Cargar", b);
        }
    }
}

src/Pasifika.WebUI/Controllers/DestacadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class DestacadoController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public DestacadoController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            List<Destacado> d = new List<Destacado>();

            if (p != null)
                d = p.Destacados.ToList();

            return PartialView(d);
        }
    }
}

src/Pasifika.WebUI/Controllers/MetatagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Pasifika.Model;
using Pasifika.Business.Abstract;

namespace Pasifika.WebUI.Controllers
{
    public class MetatagController : Controller
    {
        private readonly IPaginaBusiness _pagina;

        public MetatagController(IPaginaBusiness p)
        {
            this._pagina = p;
        }

        [ChildActionOnly]
        public PartialViewResult Cargar(int? seccionId, int? viajeId, int? notaId, int? destinoId, int? tagId, int? regionId)
        {
            var p = _pagina.Get(seccionId, viajeId, notaId, destinoId, tagId, regionId);

            if (p != null)
            {
                if (p.MetaTags.Count > 0)
                {
                    MetaTag mt = p.MetaTags.FirstOrDefault();
                    ViewBag.Title = mt.Title;
                    ViewBag.MetaDescription = mt.Description;
                    ViewBag.MetaKeywords = mt.Keywords;
                }
            }

            return PartialView();
        }
    }
}

src/Pasifika.WebUI/Areas/Admin/Views/Pagina/Edit.cshtml
@model Pasifika.WebUI.Areas.Admin.ViewModels.PaginaEditViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Pagina", FormMethod.Post, new { id = "formEdit" }))
{
    <div class="jarviswidget" id="wid-id-10">
        <header>
            <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
            <h2>Paginas </h2>

        </header>

        <!-- widget div-->
        <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
            </div>

            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">

                <div class="form-horizontal">
                    <fieldset>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Seccion</label>
                            <div class="col-md-9">
                                <select id="SeccionId" name="SeccionId" class="form-control">
                                    <option value=""></option>
                                    @foreach (var s in Model.Secciones)
                                    {
                                        <option value="@s.Id"
                                                @if (Model.Pagina.SeccionId == s.Id)
                                                {
                                                    @:selected
                                                }
                                                >@s.Nombre</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Tag</label>
                            <div class="col-md-9">
                                <select id="TagId" name="TagId" class="form-control">
                                    <option value=""></option>
                                    @foreach (var t in Model.Tags)
                                    {
                                        <option value="@t.Id"
                                                @if (Model.Pagina.TagId == t.Id)
                                                {
                                                    @:selected
                                                }
                                                >@t.Nombre</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Destino</label>
                            <div class="col-md-9">
                                <select id="TagId" name="DestinoId" class="form-control">
                                    <option value=""></option>
                                    @foreach (var d in Model.Destinos)
                                    {
                                        <option value="@d.Id"
                                                @if (Model.Pagina.DestinoId == d.Id)
                                                {
                                                    @:selected
                                                }
                                                >@d.Nombre</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-3 control-label">Region</label>
                            <div class="col-md-9">
                                <select id="TagId" name="RegionId" class="form-control">
                                    <option value=""></option>
                                    @foreach (var r in Model.Regiones)
                                    {
                                        <option value="@r.Id"
                                                @if (Model.Pagina.RegionId == r.Id) { @: selected
                                                                                                }>
                                            @r.Nombre
                                                                                            </option>
                                    }
                                </select>
                            </div>
                        </div>

                    </fieldset>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-12">
                                @Html.Hidden("Id", Model.Pagina.Id)
                                <input id="btnEnviar" type="submit" class="btn btn-primary" value="Guardar" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end widget content -->
        </div>
    </div>
}

src/Pasifika.WebUI/Areas/Admin/Views/Pagina/List.cshtml
@model Pasifika.WebUI.Areas.Admin.ViewModels.PaginaListViewModel

@{
    ViewBag.Title = "List";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<!-- Widget ID (each widget will need unique ID)-->
<div class="jarviswidget" id="wid-id-0">
    <header>
        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
        <h2>Paginas </h2>

    </header>

    <!-- widget div-->
    <div>

        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
        </div>
        <!-- end widget edit box -->
        <!-- widget content -->
        <div class="widget-body no-padding">
            <div class="row">
                <div class="col-lg-12">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th class="">Código</th>
                                <th class="col-lg-2">Seccion</th>
                                <th class="col-lg-2">Destino</th>
                                <th class="col-lg-2">Tag</th>
                                <th class="col-lg-2">Region</th>
                                <th>Banner</th>
                                <th>Destacados</th>
                                <th>Sugeridos</th>
                                <th>MetaTags</th>
                                <th>Mas Info</th>
                                <th>Texto</th>
                                <th>Banner Contextual</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody class="tbody">
                            @foreach (var p in Model.Paginas)
                            {
                                <tr data-id="@p.Id">
                                    <td>
                                        @Html.ActionLink(p.Id.ToString(), "Edit", new
                                            {
                                                id = p.Id
                                            })
                                    </td>
                                    <td>
                                        @if (p.Seccion != null)
                                        { @p.Seccion.Nombre }
                                </td>
                                <td>
                                    @if (p.Destino != null)
                                    { @p.Destino.Nombre }
                            </td>
                            <td>
                                @if (p.Tag != null)
                                { @p.Tag.Nombre }
                        </td>
                        <td>
                            @if (p.Region != null)
                            { @p.Region.Nombre }
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "Banner", new
                                            {
                                                id = p.Id
                                            }, null)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "Destacado", new
                                            {
                                                id = p.Id
                                            }, null)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "SugeridoPagina", new
                                            {
                                                id = p.Id
                                            }, null)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "Metatag", new
                                            {
                                                id = p.Id
                                            }, null)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "Inforelacion", new
                                            {
                                                id = p.Id
                                            }, null)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "PaginaTexto", new
                                            {
                                                id = p.Id
                                            }, null)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Edit", "BannerContextual", new
                            {
                                id = p.Id
                            }, null)
                    </td>
                    <td>
                        @using (Html.BeginForm("Delete", "Pagina"))
                        {
                            @Html.Hidden("Id", p.Id)
                            <input type="submit" class="btn btn-default btn-xs" value="Delete" />
                        }
                    </td>
                    </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
            <div class="widget-footer padding-bottom-10">
                @using (Html.BeginForm("Order", "Pagina", FormMethod.Post, new { id = "formEdit" }))
                {
                    @Html.Hidden("txtJsonOrden")
                    
                    <input id="btnEnviar" type="button" class="btn btn-primary" value="Guardar Orden" />
                    @Html.ActionLink("Nueva Pagina", "Create", null, new { @class = "btn btn-primary" })
                }
            </div>
        </div>
    </div>
    <!-- end widget content -->
</div>
<!-- end widget div -->

@section scripts {
    <script type="text/javascript">
    $(document).ready(function () {
        $('.tbody').sortable({}).disableSelection();

        $('#btnEnviar').click(function (e) {
            e.preventDefault();

            var orden = [];
            $('.tbody tr').each(function (i, row) {
                orden.push($(row).attr('data-id'));
            });

            $('#txtJsonOrden').val(JSON.stringify(orden));

            $("#formEdit").submit();
        });
    });
    </script>
}